<?php

namespace AppBundle\Repository;

/**
 * ChiefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiefRepository extends \Doctrine\ORM\EntityRepository
{
}
