# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    chiefs_per_page: 12

services:
    notification_factory:
        class: AppBundle\Factory\NotificationFactory
        arguments: []
    review_factory:
        class: AppBundle\Factory\ReviewFactory
        arguments: []
    request_factory:
        class: AppBundle\Factory\RequestFactory
        arguments: []
    chief_factory:
        class: AppBundle\Factory\ChiefFactory
        arguments: []
    comment_factory:
        class: AppBundle\Factory\CommentFactory
        arguments: []
    request_edit_service:
        class: AppBundle\Service\RequestEditService
        arguments: []
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
